# Generated by Django 5.2.17 on 2026-09-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('long_name', models.CharField(blank=True, max_length=120)),
                ('mode', models.CharField(choices=[('bus', 'Bus'), ('tram', 'Tram'), ('train', 'Train')], default='bus', max_length=10)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_ref', models.CharField(max_length=60, unique=True)),
                ('direction', models.PositiveSmallIntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transit.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('scheduled_arrival', models.DateTimeField(db_index=True)),
                ('actual_arrival', models.DateTimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='transit.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transit.trip')),
            ],
            options={
                'ordering': ['trip_id', 'sequence'],
                'indexes': [models.Index(fields=['stop', 'scheduled_arrival'], name='transit_sto_stop_id_ca80fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_sequence')],
            },
        ),
    ]
